version: '3.9'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./trade_project:/app
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1



  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./trade_api1:/app
    ports:
      - "8001:8001"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
